# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

Ruby: 2.2.0
osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/AYResponder.xcworkspace -scheme AYResponder-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint --allow-warnings
